config/routes.rb
GameStoreUltra::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :offers do
    collection do
      get 'search'
      post 'pagamento'
      get 'gerar_boleto'
      get 'pagamento_cartao'
      get 'pagamento_paypal'
      get 'finalizar'
      post 'create_question'
    end
  end

  resources :users do
    member do 
      get 'dashboard'
    end
  end

  root :to => 'application#index'
  match 'under_contsruction' => 'application#under_contsruction'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :offers
  attr_accessible :bio, :name, :ocupation

def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = User.find(params[:id])
    @offers = @user.offers
    respond_to do |format|
      format.html # dashboard.html.erb
      format.json { render json: @offers }
    end
  end
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :class=>"form-horizontal" do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ocupation, "Profissão" %>
    <%= f.text_field :ocupation %>
  </div>
  <div class="field">
    <%= f.label :bio, "Biografia" %>
    <%= f.text_field :bio %>
  </div>
  <div class="actions">
    <%= f.submit "Atualizar" %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>
<% if @offers.any? %>
	<h2>Minhas Ofertas</h2>
	<table class="table">
		<tbody>
	<% @offers.each do |offer| %>
		<tr>
			<td><%= link_to offer.title, offer %></td>
			<td><%= link_to offer.text, offer %></td>    
			<td><%= link_to 'Editar', edit_offer_path(offer) %></td>
    <td><%= link_to 'Apagar', offer, confirm: 'Tem certeza?', method: :delete %></td>
		</tr>
	<% end %>
		</tbody>
	</table>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Informacões do Usuário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', root_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if @users.any? %>
<table>
  <tr>
    <th>Name</th>
    <th>Ocupation</th>
    <th>Bio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.ocupation %></td>
    <td><%= user.bio %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<% end %>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Voltar', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Ocupation:</b>
  <%= @user.ocupation %>
</p>

<p>
  <b>Bio:</b>
  <%= @user.bio %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>