config/routes.rb
GameStoreUltra::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :offers do
    collection do
      get 'search'
      post 'pagamento'
      get 'gerar_boleto'
      get 'pagamento_cartao'
      get 'pagamento_paypal'
      get 'finalizar'
      post 'create_question'
    end
  end

  resources :users do
    member do 
      get 'dashboard'
    end
  end

  root :to => 'application#index'
  match 'under_contsruction' => 'application#under_contsruction'

end

app/models/offer.rb
class Offer < ActiveRecord::Base


  belongs_to :user
  belongs_to :platform_title
  has_many :offer_images
  has_many :questions

  attr_accessible :title, :price, :text, :offer_images, :offer_images_attributes
  #attr_accessor :title, :price, :text, :offer_images_attributes
  accepts_nested_attributes_for :offer_images

  validates :title, :presence => true
  validates :price, :presence => true
  validates :text, :presence => true

end

app/controllers/offers_controller.rb
# encoding:UTF-8
class OffersController < ApplicationController
  def index
    @offers = Offer.where(:user_id => current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  def search
    @offers = Offer.search(params[:search])
    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @offers }
    end
  end

  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  def new
    @offer = Offer.new
    @offer.offer_images.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def create
    @offer = Offer.new(params[:offer])
    @offer.price = params[:offer][:price].gsub("R$","").gsub(".","").gsub(",",".").to_f
    @offer.user_id = current_user.id
    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.price = params[:offer][:price].gsub("R$","").gsub(".","").gsub(",",".").to_f
    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  def create_question
    @offer= Offer.find(params[:offer_id])
    question = Question.new()
    question.user = current_user
    question.offer = @offer
    question.text = params[:text]
    respond_to do |format|
      if question.save
        format.html { redirect_to @offer, notice: 'question was successfully created.' }
        format.json { render json: question, status: :created, location: question }
      else
        format.html { render :show }
        format.json { render json: question.errors, status: :unprocessable_entity }
      end
    end
  end

  def pagamento
    tipo_pagamento = case params[:forma]
    when "Boleto" then PagamentoBoleto.new
    when "Cartão" then PagamentoCartao.new
    when "PayPal" then PagamentoPaypal.new
    else nil
    end
    pagamento = Pagamento.new(tipo_pagamento)
    action = pagamento.pagar
    redirect_to :action => action, :params => params
  end

  def gerar_boleto
    render :layout => false
  end

  def pagamento_cartao
    @bandeiras = ["selecionar bandeira:", "VISA", "MASTERCARD","AMERICAN EXPRESS"]
  end

  def pagamento_paypal
    render "finalizar"
  end

  def finalizar
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= nested_form_for @offer, :class=>"form-horizontal" do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Título" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price, "Preco" %>
    <%= f.text_field :price, :id => "dindin" %>
  </div>
  <div class="field">
    <%= f.label :text, "Texto" %>
    <%= f.text_area :text %>
  </div>
  <div class="images">
    <h3>Imagens</h3>
    <%= f.fields_for :offer_images do |offer_image| %>
      <div class="field">
        <%= offer_image.file_field :image %>
        <%= offer_image.link_to_remove "Remover Imagem" %>
      </div>
    <% end %>
    <%= f.link_to_add "Adicionar Imagem", :offer_images %>    
  </div>
  <div class="actions">
    <%= f.submit "Salvar", :class => "btn-primary btn-large" %>
  </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $("#dindin").maskMoney({showSymbol:true, symbol:"R$", decimal:",", thousands:"."});
    });
</script>

app/views/offers/edit.html.erb
<h1>Alterar Oferta</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Voltar', offers_path %>

app/views/offers/finalizar.html.erb
<h3>Obrigado por compra no GameStoreUltra!</h3>

app/views/offers/gerar_boleto.html.erb
<html>
<HEAD>
<TITLE></TITLE>
<STYLE>
td.BoletoCodigoBanco {font-size: 6mm; font-family: arial, verdana; font-weight : bold; 
					  FONT-STYLE: italic; text-align: center; vertical-align: bottom;  
					  border-bottom: 0.15mm solid #000000; border-right: 0.15mm solid #000000;
					  padding-bottom : 1mm}
td.BoletoLogo { border-bottom: 0.15mm solid #000000;  border-right: 0.15mm solid #000000;
				text-align: center; height: 10mm}	
td.BoletoLinhaDigitavel {font-size: 4 mm; font-family: arial, verdana; font-weight : bold; 
					     text-align: center; vertical-align: bottom; 
					      border-bottom: 0.15mm solid #000000; padding-bottom : 1mm; }
td.BoletoTituloEsquerdo{font-size: 0.2cm; font-family: arial, verdana; padding-left : 0.15mm;
						border-right: 0.15mm solid #000000; text-align: left}
td.BoletoTituloDireito{font-size: 2mm; font-family: arial, verdana; padding-left : 0.15mm;
						text-align: left}
td.BoletoValorEsquerdo{font-size: 3mm; font-family: arial, verdana; text-align: center;
						border-right: 0.15mm solid #000000; font-weight: bold;
						border-bottom: 0.15mm solid #000000; padding-top: 0.5mm}
td.BoletoValorDireito{font-size: 3mm; font-family: arial, verdana; text-align:right; 
					  padding-right: 3mm; padding-top: 0.8mm; border-bottom: 0.15mm solid #000000;
					   font-weight: bold;}
td.BoletoTituloSacado{font-size: 2mm; font-family: arial, verdana; padding-left : 0.15mm;
						vertical-align: top; padding-top : 0.15mm; text-align: left}
td.BoletoValorSacado{font-size: 3mm; font-family: arial, verdana;  font-weight: bold; 
					text-align : left}
td.BoletoTituloSacador{font-size: 2mm; font-family: arial, verdana; padding-left : 0.15mm;
						vertical-align: bottom; padding-bottom : 0.8mm;
						border-bottom: 0.15mm solid #000000}
td.BoletoValorSacador{font-size: 3mm; font-family: arial, verdana; vertical-align: bottom; 
					padding-bottom : 0.15mm; border-bottom: 0.15mm solid #000000;
					 font-weight: bold; text-align: left}	
td.BoletoPontilhado{border-top: 0.3mm dashed #000000; font-size: 1mm}
ul.BoletoInstrucoes{font-size : 3mm; font-family : verdana, arial}	  
</STYLE>
</HEAD>
<BODY>

<P align=center>
<TABLE cellSpacing=0 cellPadding=0 border=0 class=Boleto>
  
  <TR>
    <TD style='width: 0.9cm'></TD>
    <TD style='width: 1cm'></TD>
    <TD style='width: 1.9cm'></TD>
    
    <TD style='width: 0.5cm'></TD>
    <TD style='width: 1.3cm'></TD>
    <TD style='width: 0.8cm'></TD>
    <TD style='width: 1cm'></TD>
    
    <TD style='width: 1.9cm'></TD>
    <TD style='width: 1.9cm'></TD>
    
    <TD style='width: 3.8cm'></TD>
    
    <TD style='width: 3.8cm'></TD>
  <tr><td colspan=11>
  <ul class=BoletoInstrucoes>
  <li>Imprima em papel A4 ou Carta</li>
  <li>Utilize margens mínimas a direita e a esquerda</li>
  <li>Recorte na linha pontilhada</li>
  <li>Não rasure o código de barras</li>
  </ul>
  </td></tr>
  </TR>
  <tr><td colspan=11 class=BoletoPontilhado>&nbsp;</td></tr>
  <TR>
    <TD colspan=4 class=BoletoLogo><img src='imagens/104.jpg'></TD>
    <TD colspan=2 class=BoletoCodigoBanco>104-0</TD>
    <TD colspan=6 class=BoletoLinhaDigitavel>LinhaDigitavel</TD>
  </TR>
  <TR>
    <TD colspan=10 class=BoletoTituloEsquerdo>Local de Pagamento</TD>
    <TD class=BoletoTituloDireito>Vencimento</TD>
  </TR>
  <TR>
    <TD colspan=10 class=BoletoValorEsquerdo style='text-align: left; padding-left : 0.1cm'>LocalDePagamento</TD>
    <TD class=BoletoValorDireito>Vencimento</TD>
  </TR>  
  <TR>
    <TD colspan=10 class=BoletoTituloEsquerdo>Cedente</TD>
    <TD class=BoletoTituloDireito>Agência/Código do Cedente</TD>
  </TR>
  <TR>
    <TD colspan=10 class=BoletoValorEsquerdo style='text-align: left; padding-left : 0.1cm'>Cedente</TD>
    <TD class=BoletoValorDireito>AgenciaCodDoCedente</TD>
  </TR>   
  <TR>
    <TD colspan=3 class=BoletoTituloEsquerdo>Data do Documento</TD>
    <TD colspan=4 class=BoletoTituloEsquerdo>Número do Documento</TD>
    <TD class=BoletoTituloEsquerdo>Espécie</TD>
    <TD class=BoletoTituloEsquerdo>Aceite</TD>
    <TD class=BoletoTituloEsquerdo>Data do Processamento</TD>
    <TD class=BoletoTituloDireito>Nosso Número</TD>
  </TR>
  <TR>
    <TD colspan=3 class=BoletoValorEsquerdo>DataDoDoc</TD>
    <TD colspan=4 class=BoletoValorEsquerdo>NumeroDodoc</TD>
    <TD class=BoletoValorEsquerdo>RC</TD>
    <TD class=BoletoValorEsquerdo>N</TD>
    <TD class=BoletoValorEsquerdo>DataDoProces</TD>
    <TD class=BoletoValorDireito>NossoNumero</TD>
  </TR>  
  <TR>
    <TD colspan=3 class=BoletoTituloEsquerdo>Uso do Banco</TD>
    <TD colspan=2 class=BoletoTituloEsquerdo>Carteira</TD>
    <TD colspan=2 class=BoletoTituloEsquerdo>Moeda</TD>
    <TD colspan=2 class=BoletoTituloEsquerdo>Quantidade</TD>
    <TD class=BoletoTituloEsquerdo>(x) Valor</TD>
    <TD class=BoletoTituloDireito>(=) Valor do Documento</TD>
  </TR>
  <TR>
    <TD colspan=3 class=BoletoValorEsquerdo>&nbsp;</TD>
    <TD colspan=2 class=BoletoValorEsquerdo>SR</TD>
    <TD colspan=2 class=BoletoValorEsquerdo>R$</TD>
    <TD colspan=2 class=BoletoValorEsquerdo>&nbsp;</TD>
    <TD class=BoletoValorEsquerdo>&nbsp;</TD>
    <TD class=BoletoValorDireito><%= params[:preco] %></TD>
  </TR>  
  <TR>
    <TD colspan=10 class=BoletoTituloEsquerdo>Instruco</TD>
    <TD class=BoletoTituloDireito>(-) Desconto</TD>
  </TR>
  <TR>
    <TD colspan=10 rowspan=9 class=BoletoValorEsquerdo style='text-align: left; vertical-align:top; padding-left : 0.1cm'>Instrucoes</TD>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(-) Outras Deduções/Abatimento</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(+) Mora/Multa/Juros</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(+) Outros Acréscimos</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(=) Valor Cobrado</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>                
  <TR>
    <TD rowspan=3 Class=BoletoTituloSacado>Sacado:</TD>
    <TD colspan=8 Class=BoletoValorSacado>NomedoSacado</TD>
    <TD colspan=2 Class=BoletoValorSacado>CpfDoSacado</TD>
  </TR> 
  <TR>
    <TD colspan=10 Class=BoletoValorSacado>RuaNumeroBairro</TD>
  </TR>
  <TR>
    <TD colspan=10 Class=BoletoValorSacado>CidadeUf&nbsp;&nbsp;&nbsp;CEP</TD>
  </TR>  
  <TR>
    <TD colspan=2 Class=BoletoTituloSacador>Sacador / Avalista:</TD>
    <TD colspan=9 Class=BoletoValorSacador>NomeSacador</TD>
  </TR>
  <TR>
    <TD colspan=11 class=BoletoTituloDireito style='text-align: right; padding-right: 0.1cm'>Recibo do Sacado - Autenticação Mecânica</TD>
  </TR>
  <TR>
    <TD colspan=11 height=60 valign=top>&nbsp</TD>
  </TR>
  <tr><td colspan=11 class=BoletoPontilhado>&nbsp;</td></tr>  
  <TR>
    <TD colspan=4 class=BoletoLogo><img src='imagens/104.jpg'></TD>
    <TD colspan=2 class=BoletoCodigoBanco>104-0</TD>
    <TD colspan=6 class=BoletoLinhaDigitavel>LinhaDigitavel</TD>
  </TR>
  <TR>
    <TD colspan=10 class=BoletoTituloEsquerdo>Local de Pagamento</TD>
    <TD class=BoletoTituloDireito>Vencimento</TD>
  </TR>
  <TR>
    <TD colspan=10 class=BoletoValorEsquerdo style='text-align: left; padding-left : 0.1cm'>LocalDePagamento</TD>
    <TD class=BoletoValorDireito>Vencimento</TD>
  </TR>  
  <TR>
    <TD colspan=10 class=BoletoTituloEsquerdo>Cedente</TD>
    <TD class=BoletoTituloDireito>Agência/Código do Cedente</TD>
  </TR>
  <TR>
    <TD colspan=10 class=BoletoValorEsquerdo style='text-align: left; padding-left : 0.1cm'>Cedente</TD>
    <TD class=BoletoValorDireito>AgenciCodDoCedente</TD>
  </TR>   
  <TR>
    <TD colspan=3 class=BoletoTituloEsquerdo>Data do Doumento</TD>
    <TD colspan=4 class=BoletoTituloEsquerdo>Número do Documento</TD>
    <TD class=BoletoTituloEsquerdo>Espécie</TD>
    <TD class=BoletoTituloEsquerdo>Aceite</TD>
    <TD class=BoletoTituloEsquerdo>Data do Processamento</TD>
    <TD class=BoletoTituloDireito>Nosso Número</TD>
  </TR>
  <TR>
    <TD colspan=3 class=BoletoValorEsquerdo>DataDoDoc</TD>
    <TD colspan=4 class=BoletoValorEsquerdo>NumeroDodoc</TD>
    <TD class=BoletoValorEsquerdo>RC</TD>
    <TD class=BoletoValorEsquerdo>N</TD>
    <TD class=BoletoValorEsquerdo>DataDoProces</TD>
    <TD class=BoletoValorDireito>NossoNumero</TD>
  </TR>  
  <TR>
    <TD colspan=3 class=BoletoTituloEsquerdo>Uso do Banco</TD>
    <TD colspan=2 class=BoletoTituloEsquerdo>Carteira</TD>
    <TD colspan=2 class=BoletoTituloEsquerdo>Moeda</TD>
    <TD colspan=2 class=BoletoTituloEsquerdo>Quantidade</TD>
    <TD class=BoletoTituloEsquerdo>(x) Valor</TD>
    <TD class=BoletoTituloDireito>(=) Valor do Documento</TD>
  </TR>
  <TR>
    <TD colspan=3 class=BoletoValorEsquerdo>&nbsp;</TD>
    <TD colspan=2 class=BoletoValorEsquerdo>SR</TD>
    <TD colspan=2 class=BoletoValorEsquerdo>R$</TD>
    <TD colspan=2 class=BoletoValorEsquerdo>&nbsp;</TD>
    <TD class=BoletoValorEsquerdo>&nbsp;</TD>
    <TD class=BoletoValorDireito><%= params[:preco] %></TD>
  </TR>  
  <TR>
    <TD colspan=10 class=BoletoTituloEsquerdo>Instruco</TD>
    <TD class=BoletoTituloDireito>(-) Desconto</TD>
  </TR>
  <TR>
    <TD colspan=10 rowspan=9 class=BoletoValorEsquerdo style='text-align: left; vertical-align:top; padding-left : 0.1cm'>Instrucoes</TD>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(-) Outras Deduções/Abatimento</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(+) Mora/Multa/Juros</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(+) Outros Acréscimos</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>  
  <TR>
    <TD class=BoletoTituloDireito>(=) Valor Cobrado</TD>
  </TR>  
  <TR>
    <TD class=BoletoValorDireito>&nbsp;</TD>
  </TR>                
  <TR>
    <TD rowspan=3 Class=BoletoTituloSacado>Sacado:</TD>
    <TD colspan=8 Class=BoletoValorSacado>NomedoSacado</TD>
    <TD colspan=2 Class=BoletoValorSacado>CpfDoSacado</TD>
  </TR> 
  <TR>
    <TD colspan=10 Class=BoletoValorSacado>RuaNumeroBairro</TD>
  </TR>
  <TR>
    <TD colspan=10 Class=BoletoValorSacado>CidadeUf&nbsp;&nbsp;&nbsp;CEP</TD>
  </TR>  
  <TR>
    <TD colspan=2 Class=BoletoTituloSacador>Sacador / Avalista:</TD>
    <TD colspan=9 Class=BoletoValorSacador>NomeSacador</TD>
  </TR>
  <TR>
    <TD colspan=11 class=BoletoTituloDireito style='text-align: right; padding-right: 0.1cm'>Ficha de Compensação - Autenticação Mecânica</TD>
  </TR>
  <TR>
    <TD colspan=11 height=60 valign=top><img src='imagens/codbar.jpg'></TD>
  </TR>
  <tr><td colspan=11 class=BoletoPontilhado>&nbsp;</td></tr>  
  </TABLE></P>

</BODY>
</HTML>

app/views/offers/index.html.erb
<h1>Minhas Ofertas</h1>

<% if @offers.any? %>
<table class="table">
  <thead>
  <tr>

    <th>Título</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>
<% @offers.each do |offer| %>
  <tr>
    <td><%= link_to offer.title, offer %></td>
    <td><%= link_to 'Editar', edit_offer_path(offer) %></td>
    <td><%= link_to 'Apagar', offer, confirm: 'Tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<% end %>

<br />

<%= link_to 'Nova Oferta', new_offer_path %>

app/views/offers/new.html.erb
<h1>Nova Oferta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', offers_path %>

app/views/offers/pagamento_cartao.html.erb
<h1>Pagamento por cartão de crédito</h1>
<%= form_tag finalizar_offers_path, :method => :get do %>
	<%= select_tag :bandeira, options_for_select(@bandeiras) %><br/>
	<%= text_field_tag :numero, "", :placeholder => "número do cartão" %><br/>
  <%= submit_tag "Comprar",:class => "btn btn-primary btn-large" %><br/>
<% end %>

app/views/offers/search.html.erb
<h1>Pesquisar</h1>
<%= form_for @offers, :url => search_offers_path, :html => {:method => :get} do |f| %>
  <%= f.label :title_or_text_contains, "Título ou conteúdo do texto" %>
  <%= f.text_field :title_or_text_contains %><br />
  <%= f.submit "Pesquisar", :class => "btn-primary btn-large" %>
<% end %>
<hr/>
<% if @offers %>
	<table class = "table">
		<% @offers.each do |offer| %>
			<tr>
				<td><%= link_to offer.title, offer %></td>
				<td><%= link_to offer.price, offer %></td>
			</tr>
			<hr\>
		<% end %>
	</table>
<% end %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<h3><%= @offer.title %></h3>
</p>

<!-- <div id="myCarousel" class="carousel slide">
<ol class="carousel-indicators">
	<%# @offer.offer_images.each_with_index do |offer_image, i| %>
		<li data-target="#myCarousel" data-slide-to="<%#= i %>" <%#= i==0 ? 'class="active"' : '' %>></li>
	<%# end %>
</ol>
<div class="carousel-inner">
	<%# @offer.offer_images.each_with_index do |offer_image, i| %>
		<div class="<%#= i==0 ? 'active item' : 'item' %>">
			<%#= image_tag offer_image.image.url(:medium) %>
		</div>
	<%# end %>
</div>
<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div> -->

<p>
  <b>Título:</b>
  <%= @offer.title %>
</p>

<p>
  <b>Preço</b>
  <%= "R$ #{@offer.price}" %>
</p>

<p>
  <b>Descrição</b>
  <%= @offer.text %>
</p>

<%= link_to "Comprar", "#", :class => "btn btn-primary btn-large", :id => "botao_comprar" if current_user != @offer.user %>
<div id="tipo_compra" class="hide">
	<%= form_tag pagamento_offers_path do %>
		<%= hidden_field_tag :preco, @offer.price %>
		<%= hidden_field_tag :offer_id, @offer.id %>
		<%= label_tag :forma, "Escolha forma de pagamento:" %>
		<label class="radio">
			<%= radio_button_tag :forma, "Boleto" %>
			Boleto Bancário
		</label>
		<label class="radio">
			<%= radio_button_tag :forma, "Cartão" %>
			Cartão de crédito
		</label>
		<label class="radio">
			<%= radio_button_tag :forma, "PayPal" %>
			Paypal
		</label>
	  <%= submit_tag "Pagar", :class => "btn btn-primary" %>
	<% end %>
</div>

<%= link_to 'Editar', edit_offer_path(@offer), :class => "btn btn-primary" if @offer.user == current_user %>

<%= link_to 'Voltar', offers_path, :class => "btn btn-primary" %>

<div class="iffer_questions">
	<h3>Perguntas</h3>
	<table class="table">
		<tbody>
			<tr><td>
				<%= form_tag create_question_offers_path do %>
					<%= hidden_field_tag :user_id, current_user.id %>
					<%= hidden_field_tag :offer_id, @offer.id %>
					<%= text_area_tag :text, "", :placeholder => "úvidas? Pergunte" %>
					<br/>
					<%= submit_tag "Salvar", :class => "btn btn-primary" %>
				<% end %>
			</td></tr>
			<% @offer.questions.each do |question| %>
				<tr><td><%= question.user.name %></td><td><%= question.text %></td></tr>
			<% end %>
		</tbody>
	</table>

</div>

<script type="text/javascript">
  $(function(){
    $('#botao_comprar').click(function(evt){
      evt.preventDefault();
      $('#tipo_compra').slideDown();
    })
  })
</script>