config/routes.rb
GameStoreUltra::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :offers do
    collection do
      get 'search'
      post 'pagamento'
      get 'gerar_boleto'
      get 'pagamento_cartao'
      get 'pagamento_paypal'
      get 'finalizar'
      post 'create_question'
    end
  end

  resources :users do
    member do 
      get 'dashboard'
    end
  end

  root :to => 'application#index'
  match 'under_contsruction' => 'application#under_contsruction'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

  def index
    redirect_to dashboard_user_path(session[:user_id]) if current_user
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<hr>
	<footer id="footer">
        <p class="pull-right"><a href="#">Topo</a></p>
        <div class="links">
          <a href="https://github.com/rodrigosggouvea/game_store_ultra">GitHub</a>
        </div>
        <p>
        <br/>
        Baseado no <a target="_blank" href="http://twitter.github.com/bootstrap/">Bootstrap</a>. Hosteado no <a target="_blank" href="http://pages.github.com/">GitHub</a>. 
        Ícones do <a target="_blank" href="http://glyphicons.com/">Glyphicons</a>.
      </p>
      </footer>

app/views/application/_menu.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="brand" href="../">GAMESTOREULTRA</a>
       <div class="nav-collapse" id="main-menu">
        <ul class="nav pull-right" id="main-menu-right">
          <% if current_user %>
            <li>
              <%= link_to root_path do %> 
                Logado como <strong><%= current_user.name %></strong>!
              <% end %>
            </li>
            <li> 
              <%= link_to "Sair", signout_path, id: "sign_out" %>
            </li>
          <% else %>
            <li> 
              <%= link_to "Logar pelo Facebook", "/auth/facebook", id: "sign_in" %>
            </li>
          <% end %>
        </ul>
       </div>
     </div>
   </div>
</div>

app/views/application/_side_menu.html.erb
<%= image_tag "http://graph.facebook.com/#{User.find(current_user).uid}/picture" %>
<h4><%= User.find(current_user).name %></h4>
<ul class="nav nav-tabs nav-stacked">
	<li class="nav-header">navegação</li>
	<li class="<%= params[:action]=='dashboard' ? 'active' : '' %>">
		<%= link_to "Dashboard", dashboard_user_path(current_user) %>
	</li>
	<li class="<%= params[:controller]=='users' and params[:action]!="dashboard" ? 'active' : '' %>">
		<%= link_to "Perfil", edit_user_path(current_user) %>
	</li>
	<li class="<%= params[:action]=='search' ? 'active' : '' %>">
		<%= link_to "Pesquisar Ofertas", search_offers_path %>
	</li>
	<!--li class="<%#= params[:action]=='index' and params[:controller] == 'offers' ? 'active' : '' %>">
		<%#= link_to "Minhas Ofertas", offers_path %>
	</li-->
	<li class="<%= params[:action]=='new' and params[:controller] == 'offers' ? 'active' : '' %>">
		<%= link_to "Nova Oferta", new_offer_path %>
	</li>
</ul>

app/views/application/index.html.erb
<!-- <header class="jumbotron subhead" id="overview">
  <div class="row">
    <div class="span12">
      <h1>GameStoreUltra</h1>
      <p class="lead">Revolução no mundo brasileiro dos games!</p>
    </div>
  </div>
</header> -->

<div class="row">
  <div class="span12">
    <div style="text-align:center">
      <%= image_tag "LOGO1.png" %>
    </div>
  </div>
</div>

app/views/application/under_construction.html.erb
<div style="text-align: center">
	<%= image_tag "under_construction.png" %>
	<h1>Este site está em construção.</h1>
	<p>Em breve um novo site que irá revolucionar a vida dos gamers!</p>
</div>